name: Supabase Keep Alive
on:
  schedule:
    # Se ejecuta todos los d√≠as a las 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  clean_up:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old records from p_activo
        run: |
          curl -X DELETE "https://nhqwwqfhazpzlksiftmd.supabase.co/rest/v1/p_activo?id=gt.0" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE }}" \
          -H "Content-Type: application/json"
