name: Supabase Keep Alive Multi-Project
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  clean_up:
    runs-on: ubuntu-latest
    steps:
      - name: Proyecto 1 - Personal Links
        run: |
          curl -X DELETE "https://nhqwwqfhazpzlksiftmd.supabase.co/rest/v1/p_activo?id=gt.0" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE }}"

      - name: Proyecto 2 - Axel Movies
        run: |
          curl -X DELETE "https://fzslqxsclswkedlohgtr.supabase.co/rest/v1/p_activo?id=gt.0" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_PROYECTO_AXELMOVIES }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_PROYECTO_AXELMOVIES }}"

      - name: Proyecto 3 - Photocloud
        run: |
          curl -X DELETE "https://fmomggmoqvxysofxtykq.supabase.co/rest/v1/p_activo?id=gt.0" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_PHOTOCLOUD }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_PHOTOCLOUD }}"

      - name: Proyecto 4 - Piperavatars
        run: |
          curl -X DELETE "https://bmnmfpxorpkksczdewnp.supabase.co/rest/v1/p_activo?id=gt.0" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_PIPERAVATARS }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_PIPERAVATARS }}"
