name: Mantener Supabase Activo
on:
  schedule:
    # Se ejecuta cada 3 días a las 00:00 UTC
    - cron: '0 0 */3 * *'
  workflow_dispatch: # Botón para ejecutar manualmente

jobs:
  mantenimiento_proyectos:
    runs-on: ubuntu-latest
    steps:
      - name: Limpiar tabla proyecto 1
        run: |
          curl -X DELETE "https://fmomggmoqvxysofxtykq.supabase.co/rest/v1/p_activo" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtb21nZ21vcXZ4eXNvZnh0eWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5NzQwOTIsImV4cCI6MjA4MjU1MDA5Mn0.JB2DzJfQj_QQYlR1wKNw4mx2x3B3sDXMGLyABfDS_XQ" \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtb21nZ21vcXZ4eXNvZnh0eWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5NzQwOTIsImV4cCI6MjA4MjU1MDA5Mn0.JB2DzJfQj_QQYlR1wKNw4mx2x3B3sDXMGLyABfDS_XQ"
